import { Injectable } from '@angular/core';

@Injectable()
export class GymEnvsService {

  constructor() { }

  gymEnvIds: Array<string> = ['RoadRunner-ramDeterministic-v4',
    'Asteroids-ramDeterministic-v0',
    'Gopher-ramDeterministic-v4',
    'RoadRunner-ramDeterministic-v0',
    'KellyCoinflipGeneralized-v0',
    'Gopher-ramDeterministic-v0',
    'DoubleDunk-ramDeterministic-v4',
    'DoubleDunk-ramDeterministic-v0',
    'Robotank-ram-v0',
    'CartPole-v0',
    'CartPole-v1',
    'Asteroids-ramDeterministic-v4',
    'Pooyan-ram-v4',
    'Gopher-ram-v0',
    'Pooyan-ram-v0',
    'Gopher-ram-v4',
    'Pong-ramNoFrameskip-v0',
    'FrozenLake8x8-v0',
    'YarsRevenge-ramDeterministic-v4',
    'CarRacing-v0',
    'SpaceInvaders-ram-v0',
    'YarsRevenge-ramDeterministic-v0',
    'SpaceInvadersDeterministic-v0',
    'DoubleDunk-ram-v0',
    'SpaceInvadersDeterministic-v4',
    'DoubleDunk-ram-v4',
    'VideoPinballDeterministic-v0',
    'Centipede-v0',
    'Centipede-v4',
    'YarsRevenge-v4',
    'Pitfall-ramNoFrameskip-v0',
    'Phoenix-ram-v4',
    'SpaceInvaders-ram-v4',
    'Pitfall-ramNoFrameskip-v4',
    'Frostbite-ramNoFrameskip-v0',
    'QbertNoFrameskip-v0',
    'AmidarNoFrameskip-v4',
    'QbertNoFrameskip-v4',
    'SkiingNoFrameskip-v4',
    'SkiingNoFrameskip-v0',
    'HotterColder-v0',
    'YarsRevenge-v0',
    'Phoenix-ram-v0',
    'Berzerk-ramNoFrameskip-v4',
    'Berzerk-ramNoFrameskip-v0',
    'KungFuMaster-ramNoFrameskip-v0',
    'AirRaidNoFrameskip-v4',
    'AirRaidDeterministic-v0',
    'ChopperCommandDeterministic-v4',
    'AirRaidNoFrameskip-v0',
    'AirRaidDeterministic-v4',
    'ChopperCommandDeterministic-v0',
    'Asteroids-ram-v0',
    'Asteroids-ram-v4',
    'TutankhamDeterministic-v0',
    'KrullDeterministic-v0',
    'MsPacman-ramNoFrameskip-v0',
    'Atlantis-ramDeterministic-v0',
    'KrullDeterministic-v4',
    'MsPacman-ramNoFrameskip-v4',
    'Atlantis-ramDeterministic-v4',
    'PhoenixNoFrameskip-v4',
    'PitfallDeterministic-v0',
    'Solaris-ram-v0',
    'Solaris-ram-v4',
    'Solaris-ramNoFrameskip-v4',
    'FishingDerbyNoFrameskip-v4',
    'VentureDeterministic-v4',
    'FishingDerbyNoFrameskip-v0',
    'VentureDeterministic-v0',
    'PhoenixNoFrameskip-v0',
    'Zaxxon-ramDeterministic-v0',
    'Qbert-v4',
    'ReversedAddition-v0',
    'Qbert-v0',
    'Robotank-ram-v4',
    'Pitfall-v0',
    'Pitfall-v4',
    'BipedalWalkerHardcore-v2',
    'Venture-ram-v4',
    'Venture-ram-v0',
    'MontezumaRevenge-ramNoFrameskip-v4',
    'MontezumaRevenge-ramNoFrameskip-v0',
    'Phoenix-ramNoFrameskip-v0',
    'Go9x9-v0',
    'MountainCarContinuous-v0',
    'SemisuperPendulumNoise-v0',
    'Reacher-v1',
    'ChopperCommand-ramNoFrameskip-v0',
    'ChopperCommand-ramNoFrameskip-v4',
    'Taxi-v2',
    'ZaxxonDeterministic-v0',
    'Pong-v0',
    'Enduro-v4',
    'Tutankham-ramDeterministic-v4',
    'Enduro-v0',
    'Tutankham-ramDeterministic-v0',
    'Krull-ramNoFrameskip-v0',
    'Krull-ramNoFrameskip-v4',
    'Freeway-ramNoFrameskip-v4']

  getGymEnvIds(): Array<string> {
    return this.gymEnvIds;
  }

}
